# Generated by Django 5.1.6 on 2025-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.BigIntegerField()),
                ('area', models.IntegerField()),
                ('gdp', models.BigIntegerField()),
            ],
        ),
    ]
